/**
 * Attendance Page
 * حضور و غیاب
 */

function renderAttendance() {
    var bridge = getBridge();
    bridge.get_today_attendance().then(function(records) {
        var body = document.getElementById('attendanceBody');
        
        bridge.get_attendance_stats().then(function(stats) {
            document.getElementById('attendanceStats').textContent =
                'امروز: ' + (stats.today || 0) + ' | این هفته: ' + (stats.week || 0) + ' | این ماه: ' + (stats.month || 0);
        });
        
        if (records.length === 0) {
            body.innerHTML = '<tr><td colspan="7" class="text-muted text-center">هیچ رکورد حضوری وجود ندارد</td></tr>';
            return;
        }
        
        body.innerHTML = records.map(function(a) {
            var name = a.member_name || a.trainer_name || a.staff_name || a.user_id;
            var code = a.member_code || a.trainer_code || a.staff_code || '-';
            var type = a.user_type === 'member' ? 'عضو' : a.user_type === 'trainer' ? 'مربی' : 'کارمند';
            var status = a.check_out ? 'خروج' : 'حاضر';
            var statusClass = a.check_out ? 'secondary' : 'success';
            return '<tr>' +
                '<td><span class="badge bg-info">' + type + '</span></td>' +
                '<td>' + name + '</td>' +
                '<td>' + code + '</td>' +
                '<td>' + (a.check_in ? a.check_in.slice(11, 16) : '-') + '</td>' +
                '<td>' + (a.check_out ? a.check_out.slice(11, 16) : '-') + '</td>' +
                '<td><span class="badge bg-' + statusClass + '">' + status + '</span></td>' +
                '<td>' +
                    (!a.check_out ? '<button class="btn btn-sm btn-gold me-1" title="ثبت خروج" onclick="checkoutRecord(' + a.id + ')"><i class="fas fa-sign-out-alt"></i></button>' : '') +
                    '<button class="btn btn-sm btn-outline-gold" title="حذف رکورد" onclick="deleteAttendance(' + a.id + ')"><i class="fas fa-trash"></i></button>' +
                '</td>' +
            '</tr>';
        }).join('');
    })['catch'](function(e) { console.error(e); });
}

function quickCheckin() {
    var code = document.getElementById('attendanceCode').value.trim();
    if (!code) {
        showToast('خطا', 'لطفاً کد را وارد کنید', 'error');
        return;
    }

    // USB QR/barcode scanners usually type the scanned value into the
    // focused field. Accept both a plain code (MBR001) and the QR payload
    // generated by the application (GGYM|MBR001|...).
    if (code.indexOf('GGYM|') === 0) {
        code = code.split('|')[1] || '';
    }
    
    var bridge = getBridge();
    // Check if person exists
    bridge.get_member_by_code(code).then(function(member) {
        if (member) {
            return bridge.checkin(member.id, 'member');
        }
        return bridge.get_trainer_by_code(code).then(function(trainer) {
            if (trainer) {
                return bridge.checkin(trainer.id, 'trainer');
            }
            return bridge.get_staff_by_code(code).then(function(staff) {
                if (staff) {
                    return bridge.checkin(staff.id, 'staff');
                }
                showToast('خطا', 'کد نامعتبر است', 'error');
                return null;
            });
        });
    }).then(function(result) {
        if (result && result.att_id) {
            document.getElementById('attendanceCode').value = '';
            renderAttendance();
            showToast('ورود', 'ثبت ورود با موفقیت انجام شد');
        } else if (result) {
            showToast('خطا', result.message || 'خطا در ثبت ورود', 'error');
        }
    })['catch'](function(e) {
        showToast('خطا', 'خطا: ' + e.message, 'error');
    });
}

function quickCheckout() {
    var code = document.getElementById('attendanceCode').value.trim();
    if (!code) {
        showToast('خطا', 'لطفاً کد را وارد کنید', 'error');
        return;
    }
    
    var bridge = getBridge();
    bridge.get_today_attendance().then(function(records) {
        var record = records.find(function(r) {
            var rCode = r.member_code || r.trainer_code || r.staff_code;
            return rCode === code && !r.check_out;
        });
        if (!record) {
            showToast('خطا', 'هیچ حضور فعالی برای این کد یافت نشد', 'error');
            return;
        }
        bridge.checkout(record.id).then(function() {
            document.getElementById('attendanceCode').value = '';
            renderAttendance();
            showToast('خروج', 'ثبت خروج با موفقیت انجام شد');
        });
    })['catch'](function(e) {
        showToast('خطا', 'خطا: ' + e.message, 'error');
    });
}

function checkoutRecord(id) {
    var bridge = getBridge();
    bridge.checkout(id).then(function() {
        renderAttendance();
        showToast('خروج', 'ثبت خروج با موفقیت انجام شد');
    })['catch'](function(e) {
        showToast('خطا', 'خطا: ' + e.message, 'error');
    });
}

function deleteAttendance(id) {
    if (confirm('آیا از حذف این رکورد حضوری اطمینان دارید؟')) {
        var bridge = getBridge();
        bridge.delete_attendance(id).then(function(result) {
            if (result && result.success) {
                renderAttendance();
                showToast('حذف', 'رکورد با موفقیت حذف شد');
            } else {
                showToast('خطا', (result && result.message) || 'خطا در حذف', 'error');
            }
        })['catch'](function(e) {
            showToast('خطا', 'خطا: ' + e.message, 'error');
        });
    }
}
